
### custom configurations
# env
export LS_COLORS='di=00;36:fi=00;37'
export PATH=$PATH:.

# alias
alias vb='vi ~/.bashrc'
alias sb='source ~/.bashrc'
alias wn='watch -n 0.5 nvidia-smi'
alias jn='jupyter notebook --allow-root &'
